spring:
  rabbitmq:
    host: YOUR_RABBITMQ_ADDRESS # EX) 127.0.0.1
    port: YOUR_RABBITMQ_PORT # EX) 1234
    username: YOUR_RABBITMQ_USERNAME #EX) user
    password: YOUR_RABBITMQ_PASSWORD #EX) password
    listener:
      acknowledge-mode: auto
      default-requeue-rejected: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://YOUR_POSRGRESQL_URL:PORT/DBNAME?charSet=UTF-8&prepareThreshold=1
    # EX) url: jdbc:postgresql://127.0.0.1:1234/mydb?charSet=UTF-8&prepareThreshold=1
    username: DB_USERNAME # EX) dbuser
    password: DB_PASSWORD # EX) password
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 3
      maximum-pool-size: 20
      pool-name: gdoDBPool
      auto-commit: false
server:
  port: 8080 
  context-path: /geodt 
gitrnd:
  serverhost: THE_PUBLIC_PROD_SERVER_ADDRESS_NOT_LOCALHOST # EX) 175.111.222.34
  apache:
    basedir: gdofiles # THE_DIRECTORY_WHERE_FILES_ARE_DOWNLOADED
  rabbitmq:
    queue: YOUR_RABBITMQ_QUEUE_NAME #EX) queue1
mybatis:
  config-location: classpath:config/mybatis.xml
  mapper-location: classpath:sql/*.xml
  configuration:
    map-underscore-to-camel-case: true
    use-column-label: true